// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SuperShop.Models.Data;

#nullable disable

namespace SuperShop.Migrations
{
    [DbContext(typeof(FakeDexContext))]
    [Migration("20221115171446_default")]
    partial class @default
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");

            modelBuilder.Entity("SuperShop.Models.Data.Shipping", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("AddressD")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("addressD");

                    b.Property<string>("AddressO")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("addressO");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IdUser")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("idUser");

                    b.Property<string>("NameD")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nameD");

                    b.Property<string>("NameO")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nameO");

                    b.Property<double>("PriceD")
                        .HasColumnType("double")
                        .HasColumnName("priceD");

                    b.Property<double>("PriceP")
                        .HasColumnType("double")
                        .HasColumnName("priceP");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<double>("Total")
                        .HasColumnType("double")
                        .HasColumnName("total");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "IdUser" }, "IX_Shipping_idUseremail");

                    b.ToTable("Shipping", (string)null);
                });

            modelBuilder.Entity("SuperShop.Models.Data.Tracking", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Latitud")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("latitud");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("location");

                    b.Property<string>("Longitud")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("longitud");

                    b.Property<long>("ShippingId")
                        .HasColumnType("bigint")
                        .HasColumnName("shippingId");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ShippingId" }, "IX_Tracking_shippingIdId");

                    b.ToTable("Tracking", (string)null);
                });

            modelBuilder.Entity("SuperShop.Models.Data.User", b =>
                {
                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<bool>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("isAdmin");

                    b.HasKey("Email")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Email" }, "IX_User_email")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
