version: '3.8'

services:
  fakedex-db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: s3cur3P4ssw0rd
      MYSQLDB_USER: mysql
    restart: always
    container_name: fakedex-db
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - local-network

  fakedex-api:
    depends_on:
      - fakedex-db
    container_name: fakedex-api
    image: fakedex-api
    environment:
      SRING_DATASOURCE.URL: jdbc:mysql://fakedex-db:3306/FakeDex?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SRING_DATASOURCE.USERNAME: root
      SRING_DATASOURCE.PASSWORD: s3cur3P4ssw0rd
      # SRING_JPA_PROPERTIES.HIBERNATE.DIALECT: org.hibernate.dialect.MySQL5InnoDBDialect
      SRING_JPA_HIBERNATE.DDL-AUTO": none
    build: 
      dockerfile: ./Dockerfile
      context: ./
    restart: always
    ports:
      - "5000:5000"
    networks:
      - local-network
    
volumes:
  mysql-data:
    driver: local
    
networks:
  local-network:
    driver: bridge