version: '3.8'

services:
  fakedex-db:
    image: mysql
    ports:
      - "5432:5432"
    environment:
      MYSQL_ROOT_PASSWORD: s3cur3P4ssw0rd
      MYSQLDB_USER: mysql
    restart: always
    container_name: fakedex-db
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - local-network

  fakedex-api:
    depends_on:
      - fakedex-db
    container_name: fakedex-api
    image: fakedex-api
    environment:
      SPRING_APPLICATION_JSON: 
        '{
          "spring.datasource.url": "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
          "spring.datasource.username": "$MYSQLDB_USER",
          "spring.datasource.password": "$MYSQLDB_ROOT_PASSWORD",
          "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL5InnoDBDialect",
          "spring.jpa.hibernate.ddl-auto": "update"
        }'
    build: 
      dockerfile: ./Dockerfile
      context: ./
    restart: always
    ports:
      - "5000:5000"
    
volumes:
  mysql-data:
    driver: local
    
networks:
  local-network:
    driver: bridge