# version: '3.8'

# services:
#   super-shop-db:
#     image: postgres
#     ports:
#     - "5432:5432"
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: s3cur3P4ssw0rd
#     restart: always
#     container_name: super-shop-db
#     volumes:
#       - postgres-data:/var/lib/postgresql/data
#     networks:
#        - local-network
  
#   super-shop-api:
#     depends_on: 
#      - super-shop-db
#     container_name: super-shop-api
#     image: super-shop-api
#     environment:
#       ASPNETCORE_ENVIRONMENT: Docker
#     build:
#       dockerfile: ../super-shop-backend/SuperShop/Dockerfile
#       context: ../
#     restart: always
#     ports:
#       - "5000:5000"
#     entrypoint: dotnet /app/SuperShop.dll

# volumes:
#   postgres-data:
#     driver: local
    
# networks:
#   local-network:
#     driver: bridge

version: '3.8'

services:
  fakedex-db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: s3cur3P4ssw0rd
      MYSQLDB_USER: mysql
    restart: always
    container_name: fakedex-db
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - local-network
  
  fakedex-api:
    depends_on: 
     - fakedex-db
    container_name: fakedex-api
    image: fakedex-api
    environment:
       ASPNETCORE_ENVIRONMENT: Docker
    build:
      dockerfile: ../super-shop-backend/SuperShop/Dockerfile
      context: ../
    restart: always
    ports:
      - "5000:5000"
    entrypoint: dotnet /app/SuperShop.dll

volumes:
  mysql-data:
    driver: local
    
networks:
  local-network:
    driver: bridge